name: Splunk App CI/CD
description: A reusable GitHub Action for packaging, testing, and publishing Splunk apps.
author: Will Searle <splunk@livehybrid.com>

inputs:
  python-version:
    description: Python version to use for the environment.
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip

      - name: Setup Environment
        shell: bash
        run: |
          echo "splunk-add-on-ucc-framework" > requirements_dev.txt
          pip install splunk-add-on-ucc-framework

      - name: Determine Version
        id: version
        shell: bash
        run: |
          echo "Version is now calculated by ucc-gen"
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          ref_type=${GITHUB_REF#refs/*/}
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG_VERSION=${GITHUB_REF#refs/tags/v}
          else
            TAG_VERSION="1.0.0"
          fi
          VERSION_WITH_HASH="${TAG_VERSION}+${SHORT_COMMIT_HASH}"
          echo "VERSION_WITH_HASH=${VERSION_WITH_HASH}" >> $GITHUB_OUTPUT

      - name: Generate app with ucc-gen
        uses: splunk/addonfactory-ucc-generator-action@v3.0.0
        with:
          version: ${{ steps.version.VERSION_WITH_HASH }}

      - name: Generate Package tarball
        shell: bash
        run: |
          mkdir -p dist
          mv output/* output/app
          ucc-gen package -o dist --path output/app

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v5
        with:
          name: dist
          path: dist/*

